<?xml version="1.0"?>
<robot name="foilboat" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find boat_description_ros_deb)/urdf/materials.xacro" />
  <xacro:include filename="$(find boat_description_ros_deb)/urdf/foilboat_components.xacro" />
  <xacro:include filename="$(find boat_description_ros_deb)/urdf/macros.xacro" />

  <xacro:property name="length" value="5.25" />
  <xacro:property name="width" value="2.59" />

  <xacro:property name="hullMass" value="40" />
  <xacro:property name="hullX" value="${length}" />
  <xacro:property name="hullY" value="0.3" />
  <xacro:property name="hullZ" value="0.5" />

  <xacro:property name="beamMass" value="15" />
  <xacro:property name="beamX" value="0.2" />
  <xacro:property name="beamY" value="${width - hullZ}" />
  <xacro:property name="beamZ" value="0.1" />

  <link name="base_link" />

  <xacro:beam name="front" front="1" />
  <xacro:beam name="back" front="-1"/>

  <xacro:hull name="left" port="1" />
  <xacro:hull name="right" port="-1" />

  <link name="toughsonic_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.1"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.1" />
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1" />
      <xacro:sphere_inertia m="1" r="0.1" />
    </inertial>
  </link>

  <joint name="toughsonic_link_joint" type="fixed">
    <parent link="front_beam"/>
    <child link="toughsonic_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="sensor_box_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.1"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.1" />
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1" />
      <xacro:sphere_inertia m="1" r="0.1" />
    </inertial>
  </link>

  <joint name="sensor_box_link_joint" type="fixed">
    <parent link="front_beam" />
    <child link="sensor_box_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>

  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.1"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.1" />
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1" />
      <xacro:sphere_inertia m="1" r="0.1" />
    </inertial>
  </link>

  <joint name="imu_link_joint" type="fixed">
    <parent link="sensor_box_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="${pi} 0 0"/>
  </joint>

  <!-- GPS -->
  <link name="m8u">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.1"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.1" />
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1" />
      <xacro:sphere_inertia m="1" r="0.1" />
    </inertial>
  </link>

  <joint name="m8u_joint" type="fixed">
    <parent link="sensor_box_link"/>
    <child link="m8u"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>